apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phrases

images:
- name: frontend
  newTag: v1
  newName: frontend

resources:
- configmap.yaml
- deployment.yaml
- hpa.yml
- service.yaml
- httproute.yaml