apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app.yaml

images:
- name: ghcr.io/adhatcher/frontend_api
  newName: ghcr.io/adhatcher/frontend_api
  newTag: 319dfb3e118079a3890fc96207331f118de9a05b
